version: '3'
services:

  #NODE Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      PORT: 3030
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: rurh64u493s
      SERVICE_NAME: app
      SERVICE_TAGS: 
    ports:
      - "3030:3000"
    volumes:
      - ./:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: school
      MYSQL_ROOT_PASSWORD: 9j5gyg5t
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./database/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
  node_modules: